env:
  global:
    - ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true

matrix:
  include:
  - os: osx
    osx_image: xcode9.4
    language: node_js
    node_js: "10"
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

  - os: linux
    language: node_js
    node_js: "10"
    sudo: required
    dist: xenial
    addons:
      snaps:
        - name: snapcraft
          classic: true
    env:
      - ELECTRON_CACHE=$HOME/.cache/electron
      - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    before_install:
      - sudo apt-get update
      - sudo apt-get install -y gcc-multilib g++-multilib

script:
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    echo $SNAP_TOKEN | snapcraft login --with -
    yarn && yarn test && yarn release -l
  else
    yarn && yarn test && yarn release -m
  fi

branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
