name: ci-bin-builder
on:
  push:
  pull_request:
  release:

jobs:
  build-linux64-multilib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1
      - run: |
          export ELECTRON_CACHE=$HOME/.cache/electron
          export ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder      
        name: Export variables
      - run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib
        name: Install multilib GCC and G++
      - run: |
          yarn && yarn test && yarn release -l --publish never
        name: Run build
      - uses: actions/upload-artifact@v2
        with:
          name: DDMM-linux64-dist-AppImage
          path: dist/*.AppImage
  build-darwin:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1
      - run: |
          export ELECTRON_CACHE=$HOME/.cache/electron
          export ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder      
        name: Export variables
      - run: |
          yarn && yarn test && yarn release -m --publish never
        name: Run build
      - uses: actions/upload-artifact@v2
        with:
          name: DDMM-darwin-dist-dmg
          path: dist/*.dmg
  build-win64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1
      - run: |
          yarn && yarn test && yarn release -w --publish never
      - uses: actions/upload-artifact@v2
        with:
          name: DDMM-win64-dist
          path: dist
